### PR TITLE
ap-quest-icon

### PR DESCRIPTION
**Pull request by nazartokar**

### CODE REVIEW

**Review by jarrodek — COMMENTED** [review]
Why to prefix name with "anypoint" in the icon library scoped as "anypoint"? :)

**Review by jarrodek — APPROVED** [review]
Never mind. I've noticed that other icons has the same prefix.

**Comment by nazartokar** [comment]
@jarrodek yeap, there're other `anypoint` icons with this prefix. BTW, could you also uprise the repo version after the merge please?

**Comment by jarrodek** [comment]
It's merging to `anypoint` branch, it's not to be released. Bower is set to track this branch.

**Pull request merged**
